# Generated by Django 5.0.1 on 2025-02-03 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmmaker',
            fields=[
                ('filmmaker_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('profile_image', models.ImageField(upload_to='profile_images/')),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('usertype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('theater_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('film_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('duration', models.PositiveIntegerField()),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.filmmaker')),
            ],
        ),
        migrations.AddField(
            model_name='filmmaker',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.login'),
        ),
        migrations.CreateModel(
            name='ContentManager',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('profile_image', models.ImageField(upload_to='profile_images/')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('audience_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('preferences', models.TextField()),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.login')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('campaign_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.film')),
                ('filmmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.filmmaker')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.contentmanager')),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('target_audience', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.contentmanager')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.marketingcampaign')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.contentmanager')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField()),
                ('review_date', models.DateTimeField()),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.audience')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.film')),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningSlot',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.film')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.theater')),
            ],
        ),
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_status', models.CharField(max_length=20)),
                ('booking_date', models.DateTimeField()),
                ('audience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.audience')),
                ('filmmaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.filmmaker')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.screeningslot')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer', to='bridgeApp.login')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='bridgeApp.login')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.seatbooking')),
            ],
        ),
        migrations.CreateModel(
            name='TheaterOwner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('profile_image', models.ImageField(upload_to='profile_images/')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.login')),
            ],
        ),
        migrations.AddField(
            model_name='theater',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.theaterowner'),
        ),
        migrations.CreateModel(
            name='TheaterSeat',
            fields=[
                ('seat_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_number', models.CharField(max_length=10)),
                ('seat_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.theater')),
            ],
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.theaterseat'),
        ),
    ]
