# Generated by Django 4.1 on 2025-03-28 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('audience_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('preferences', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('chatid', models.AutoField(primary_key=True, serialize=False)),
                ('fromid', models.CharField(max_length=225)),
                ('toid', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('message', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='ContentManager',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('profile_image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='film',
            fields=[
                ('filmid', models.AutoField(primary_key=True, serialize=False)),
                ('film_name', models.CharField(max_length=225)),
                ('deatils', models.CharField(max_length=225)),
                ('photo', models.FileField(upload_to='')),
                ('date', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Filmmaker',
            fields=[
                ('filmmaker_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('profile_image', models.CharField(max_length=255)),
                ('bio', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('usertype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notifications', models.CharField(max_length=225)),
                ('title', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningSlot',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.film')),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('theater_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TheaterSeat',
            fields=[
                ('seat_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_number', models.CharField(max_length=10)),
                ('seat_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('slot', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.screeningslot')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.theater')),
            ],
        ),
        migrations.CreateModel(
            name='TheaterOwner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('license_photo', models.CharField(max_length=255)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.login')),
            ],
        ),
        migrations.AddField(
            model_name='theater',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.theaterowner'),
        ),
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_status', models.CharField(max_length=20)),
                ('booking_date', models.DateTimeField()),
                ('audience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.audience')),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.film')),
                ('filmmaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.filmmaker')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.theaterseat')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.screeningslot')),
            ],
        ),
        migrations.AddField(
            model_name='screeningslot',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.theater'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(max_length=255)),
                ('review_text', models.CharField(max_length=255)),
                ('review_date', models.CharField(max_length=255)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.audience')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.film')),
            ],
        ),
        migrations.CreateModel(
            name='PromoMaterial',
            fields=[
                ('promo_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('release_date', models.CharField(max_length=50)),
                ('poster', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255, null=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.film')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.seatbooking')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer', to='bridgeApp.login')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='bridgeApp.login')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('campaign_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.film')),
                ('filmmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.filmmaker')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.contentmanager')),
            ],
        ),
        migrations.AddField(
            model_name='filmmaker',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.login'),
        ),
        migrations.AddField(
            model_name='film',
            name='filmmaker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.filmmaker'),
        ),
        migrations.AddField(
            model_name='contentmanager',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.login'),
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('complaintid', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.CharField(max_length=225)),
                ('reply', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('senderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.login')),
            ],
        ),
        migrations.CreateModel(
            name='BookTheaters',
            fields=[
                ('Booktheater_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=225)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.film')),
                ('fimmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.filmmaker')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.theater')),
            ],
        ),
        migrations.AddField(
            model_name='audience',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.login'),
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('target_audience', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.marketingcampaign')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.contentmanager')),
            ],
        ),
    ]
