# Generated by Django 5.0.1 on 2025-02-03 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('complaintid', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.CharField(max_length=225)),
                ('reply', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('senderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.login')),
            ],
        ),
    ]
