# Generated by Django 5.0.1 on 2025-02-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeApp', '0002_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='film_id',
            new_name='filmid',
        ),
        migrations.RemoveField(
            model_name='film',
            name='director',
        ),
        migrations.RemoveField(
            model_name='film',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='film',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='film',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='film',
            name='title',
        ),
        migrations.AddField(
            model_name='film',
            name='date',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='deatils',
            field=models.CharField(default=11, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='film_name',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='photo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
