# Generated by Django 5.0.1 on 2025-02-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeApp', '0003_rename_film_id_film_filmid_remove_film_director_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('chatid', models.AutoField(primary_key=True, serialize=False)),
                ('fromid', models.CharField(max_length=225)),
                ('toid', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('message', models.CharField(max_length=225)),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='notifications',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.CharField(max_length=225),
        ),
    ]
