# Generated by Django 5.0.1 on 2025-02-03 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeApp', '0004_chat_remove_notification_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.theaterowner'),
        ),
    ]
