# Generated by Django 4.1 on 2025-02-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeApp', '0005_alter_theater_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='preferences',
            field=models.CharField(max_length=225),
        ),
    ]
