# Generated by Django 5.0.1 on 2025-02-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeApp', '0005_alter_theater_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theaterowner',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='theaterowner',
            name='license_photo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
