# Generated by Django 4.1 on 2025-02-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeApp', '0007_theaterseat_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmmaker',
            name='bio',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='filmmaker',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='filmmaker',
            name='profile_image',
            field=models.CharField(max_length=255),
        ),
    ]
