# Generated by Django 4.1 on 2025-02-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeApp', '0008_alter_filmmaker_bio_alter_filmmaker_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmanager',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contentmanager',
            name='profile_image',
            field=models.CharField(max_length=255),
        ),
    ]
