# Generated by Django 4.1 on 2025-02-05 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeApp', '0009_alter_contentmanager_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='filmmaker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.filmmaker'),
        ),
    ]
