# Generated by Django 4.1 on 2025-02-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeApp', '0010_film_filmmaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.CharField(max_length=255),
        ),
    ]
