# Generated by Django 4.1 on 2025-02-07 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeApp', '0006_remove_theaterowner_profile_image_and_more'),
        ('bridgeApp', '0011_alter_review_rating_alter_review_review_date_and_more'),
    ]

    operations = [
    ]
