# Generated by Django 4.1 on 2025-02-28 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeApp', '0012_merge_20250207_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theaterowner',
            name='license_photo',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='PromoMaterial',
            fields=[
                ('promo_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('release_date', models.CharField(max_length=50)),
                ('poster', models.CharField(max_length=255)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.film')),
            ],
        ),
    ]
