# Generated by Django 4.1 on 2025-02-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeApp', '0013_alter_theaterowner_license_photo_promomaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promomaterial',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
