# Generated by Django 4.1 on 2025-03-03 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeApp', '0014_promomaterial_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTheaters',
            fields=[
                ('Booktheater_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=225)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.film')),
                ('fimmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.filmmaker')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridgeApp.theater')),
            ],
        ),
    ]
